### ISSUE TITLE
current step highlighting

### ISSUE THREAD

**Issue by tbchamp** [tbchamp/UWCSE403-Recipe-Reader#24]
the current step should be highlighted for the user while navigating the recipe

**Comment by aosobov** [comment]
Should be in the next release

**Comment by yamana** [comment]
Implemented. Highlighting is green to match our app. Feel free to change the color by changing the HIGHLIGHTING_COLOR at the top of RecipeViewActivity.java and InstructionsFragment.java. First instruction is highlighted when just viewing the instructions (not the instructions list after pressing "Start"), but this is difficult to change due to the way our app retrieves the same instruction fragment for both of those buttons.
